<?php
/**
 * @file
 * Lets users add private annotations to nodes.
 *
 * DRUPAL 7 Practice
 * Adds a text field when a node is displayed
 * so that authenticated users may make notes.
 */

/**
 *  Implementation of hook_menu().
 */

function d7_cus_menu(){

    $items['admin/config/d7_cus']= array(
        'title'=>' D7 Node annotation',
        'description'=>'Adjust node annotation options.',
        'position'=>'center',
        'weight'=>0,
        'page callback'=>'system_admin_menu_block_page',
        'access arguments'=>array('adminster site configuration'),
        'file'=>'system.admin.inc',
        'file path'=>drupal_get_path('module', 'system'),
        );
    $items['admin/config/d7_cus/settings']=array(
        'title'=>'D7 Annotation settings',
        'description'=>'Change how annotations behave.',
        'page callback' =>'drupal_get_form',
        'page arguments'=> array('annotate_admin_settings'),
        'access arguments'=>array('adminster site configuration'),
        'type'=> MENU_NORMAL_ITEM,
        'file'=>'annotate.admin.inc',
        );
    return $items;
}